// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	cats "no_vcs/me/channels/internal/cats"

	mock "github.com/stretchr/testify/mock"
)

// GetCatByID is an autogenerated mock type for the GetCatByID type
type GetCatByID struct {
	mock.Mock
}

// ByID provides a mock function with given fields: id
func (_m *GetCatByID) ByID(id int) (*cats.Cat, error) {
	ret := _m.Called(id)

	var r0 *cats.Cat
	if rf, ok := ret.Get(0).(func(int) *cats.Cat); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cats.Cat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
